### ISSUE TITLE
Program received signal SIGSEGV: Segmentation fault - invalid memory reference

### ISSUE THREAD

**Issue by tetsufmbio** [m3g/lovoalign#1]
Hello! I'm getting a Segmentation fault when I try to execute lovoalign with the protein attached. It returns the error even when I try to align it with itself. Could you please help me?

Here is the message:
> ./lovoalign -p1 test_protein.txt -p2 test_protein.txt
  #######################################################################

                                LOVOALIGN
             Convergent algorithms for protein structural alignment
     Martinez, Andreani, and Martinez, BMC Bioinformatics, 8:306, 2007
                              Version 21.027

  #######################################################################
At line 41 of file ioformat.f90
Fortran runtime error: Substring out of bounds: upper bound (201) of 'hash_line' exceeds string length (200)

Error termination. Backtrace:
#0  0x7f81a5b05d21 in ???
#1  0x7f81a5b06869 in ???
#2  0x7f81a5b06ee6 in ???
#3  0x55e610c8781a in ???
#4  0x55e610c87bee in ???
#5  0x55e610c8628e in ???
#6  0x7f81a57c8082 in ???
#7  0x55e610c862ed in ???
#8  0xffffffffffffffff in ???

[test_protein.txt](https://github.com/m3g/lovoalign/files/10730669/test_protein.txt)

**Comment by lmiq** [comment]
I don´t get the error here, but anyway I changed something that I think will solve your problem. You can download the updated version here:

https://github.com/m3g/lovoalign/releases/tag/22.0.0

Please let me know if now it works for you.

**Comment by tetsufmbio** [comment]
Yes! Now it is working fine! Thank you!
