### ISSUE TITLE
Lovoalign not initializing 

### ISSUE THREAD

**Issue by Bhavika-131** [m3g/lovoalign#2]
Lovoalign command is not working even after making the package. Can't confirm if it is even being installed or not. 
Need to use it BAT.py. Please resolve this issue ASAP

**Comment by lmiq** [comment]
I need more info. Please describe exactly what you are doing and the error messages you get.

**Comment by Bhavika-131** [comment]
I'm trying to install Lovoalign in my path to use it with BAT.py, an automated ligand binding affinity tool. 
After I installed lovoalign, (as directed on the website, https://www.ime.unicamp.br/~martinez/lovoalign/software.html ), I tried running the command 'lovoalign' but it gives error and says :
" lovoalign: command not found "

I've tried running it in path with OPENMM and AmberTools both. 
It is also not showing up in the list of installed packages in my conda env. 
What could be the possible issue?

Thanks for replying.

**Comment by lmiq** [comment]
Most likely you need to add the `lovoalign` executable to your path environment variable.

Or, just to check, if you are in the directory where it is installed, use `./lovoalign`  (with the `./`).

I don't think it will show in the conde environment. It is not a python package. I don't know either how `BAT.py` works with it (I have nothing to do with `BAT.py`, never heard of it actually). If it requires `lovoalign` and that is not working, probably the problem is with `BAT.py`.

**Comment by lmiq** [comment]
Just took a look at the `BAT.py` page and, effectively, what you need is to add `lovoalign` to your path environment variable.

**Comment by Bhavika-131** [comment]
I'm sorry but I did add it the path environment variable i.e `~bashrc.`

Lovoalign is only working as a standalone program in its bin file. BAT.py isn't able to call it unfortunately. 
Is there a specific method that I need to follow to put it in my path env variable?
It would be extremely helpful if you could provide that.

**Comment by lmiq** [comment]
Here, for example, I have `lovoalign` installed at:

```
leandro@m3g:~/programs/lovoalign/bin% pwd
/home/leandro/programs/lovoalign/bin
```

Thus, I need to add the following line to the `.bashrc` file:

```
PATH=$PATH:/home/leandro/programs/lovoalign/bin
```

With that, and after restarting the terminal (or running `source ~/.bashrc`), `lovoalign ` is available from anywhere.

If that is going to make `BAT.py` find it, **I don't know**. If it does not, you should open an issue in the `BAT.py` repository.

**Comment by Bhavika-131** [comment]
Thank you for the Path sourcing suggestion, it worked and I obtained my results.
